name: Run Dast

on:
  workflow_dispatch:
jobs:
  dast:
    runs-on: ubuntu-latest
    steps:
    - name: ZAP Scan
      uses: zaproxy/action-api-scan@v0.3.0
      with:
        target: 'http://151.250.222.135:18080/api/cmd'
