name: Run Dast

on:
  push:
    branches:
      - main

jobs:
  dast:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20.1

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build and run API server
      run: |
        export LOCAL=true
        go run cmd/main.go &

    - name: Install OWASP ZAP
      run: |
        wget -q https://github.com/zaproxy/zaproxy/releases/download/w2023-06-28/ZAP_WEEKLY_D-2023-06-28.zip
        unzip ZAP_WEEKLY_D-2023-06-28.zip
        export PATH=$PWD/ZAP_D-2023-06-28:$PATH

    - name: Run DAST
      run: |
        ./ZAP_D-2023-06-28/zap.sh -t http://localhost:18080/api/cmd -r dast-report.html


    - name: Upload DAST report
      uses: actions/upload-artifact@v2
      with:
        name: dast-report
        path: dast-report.html
