name: Run Dast

on:
  push:
    branches:
      - main

jobs:
  dast:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20.1

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build and run API server
      run: |
        export LOCAL=true
        go run cmd/main.go &
    - name: ZAP Scan
      uses: zaproxy/action-api-scan@v0.3.0
      with:
        target: 'http://localhost:18080/api/cmd'

    - name: Upload DAST report
      uses: actions/upload-artifact@v2
      with:
        name: dast-report
        path: report_html.html
